-- =======================================================
-- 1. DATABASE SETUP
-- =======================================================
CREATE DATABASE IF NOT EXISTS attendance_system;
USE attendance_system;

-- =======================================================
-- 2. USERS TABLE
-- =======================================================
-- Stores both students and lecturers
-- 'role' allows the application to distinguish permissions
CREATE TABLE users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id VARCHAR(50) UNIQUE NOT NULL, -- Admission No (Students) or Staff ID (Lecturers)
    full_name VARCHAR(100) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,      -- Store HASHED passwords only (e.g., Bcrypt)
    role ENUM('student', 'lecturer') NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- =======================================================
-- 3. UNITS TABLE
-- =======================================================
CREATE TABLE units (
    id INT AUTO_INCREMENT PRIMARY KEY,
    unit_code VARCHAR(50) NOT NULL,
    unit_name VARCHAR(100) NOT NULL,
    lecturer_id INT,
    FOREIGN KEY (lecturer_id) REFERENCES users(id)
        ON DELETE SET NULL
);

-- =======================================================
-- 4. SESSIONS TABLE
-- =======================================================
CREATE TABLE sessions (
    id INT AUTO_INCREMENT PRIMARY KEY,
    unit_code VARCHAR(20) NOT NULL,
    lecturer_id INT NOT NULL,
    qr_token VARCHAR(255),               -- Dynamic token generated by the app for the QR code
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (unit_code) 
        REFERENCES units(unit_code) 
        ON DELETE CASCADE,

    FOREIGN KEY (lecturer_id) 
        REFERENCES users(id) 
        ON DELETE CASCADE
);

-- =======================================================
-- 5. ATTENDANCE TABLE
-- =======================================================
CREATE TABLE attendance (
    id INT AUTO_INCREMENT PRIMARY KEY,
    session_id INT NOT NULL,
    student_id INT NOT NULL,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    status ENUM('Present', 'Late', 'Absent') DEFAULT 'Present',

    FOREIGN KEY (session_id) 
        REFERENCES sessions(id) 
        ON DELETE CASCADE,

    FOREIGN KEY (student_id) 
        REFERENCES users(id) 
        ON DELETE CASCADE,

    -- Ensures a student cannot be marked present twice for the exact same session ID
    UNIQUE KEY unique_attendance (session_id, student_id)
);

-- =======================================================
-- 6. SEED DATA (Dynamic Insertion)
-- =======================================================

-- A. Insert Users
-- Note: In a real app, passwords must be hashed by the backend before insertion.
-- The hash below is a placeholder for 'password123'
INSERT INTO users (user_id, full_name, email, password, role) VALUES
('L-001', 'Dr. Smith', 'smith@university.ac.ke', '$2b$10$hashedpasswordplaceholder', 'lecturer'),
('SCT-001', 'Ian Mukaramoja', 'ian@student.ac.ke', '$2b$10$hashedpasswordplaceholder', 'student'),
('SCT-002', 'Jane Doe', 'jane@student.ac.ke', '$2b$10$hashedpasswordplaceholder', 'student');

-- B. Insert Units
-- REMOVED HARD CODING: instead of VALUES (..., 1), we look up Dr. Smith's ID dynamically.
INSERT INTO units (unit_code, unit_name, lecturer_id) VALUES
('CCS 401', 'Network Security', (SELECT id FROM users WHERE user_id = 'L-001')),
('CCS 302', 'Database Systems', (SELECT id FROM users WHERE user_id = 'L-001'));

-- C. Insert a Test Session (Optional)
-- Creates a session for Network Security run by Dr. Smith
INSERT INTO sessions (unit_code, lecturer_id, qr_token, is_active) VALUES
('CCS 401', (SELECT id FROM users WHERE user_id = 'L-001'), 'test_qr_token_123', TRUE);

-- D. Insert Test Attendance (Optional)
-- Marks Ian Mukaramoja present for the session created above
INSERT INTO attendance (session_id, student_id, status) VALUES
(
    (SELECT id FROM sessions WHERE qr_token = 'test_qr_token_123' LIMIT 1), -- Get Session ID
    (SELECT id FROM users WHERE user_id = 'SCT-001'),                       -- Get Student ID
    'Present'
);

ALTER TABLE sessions ADD COLUMN latitude DECIMAL(10, 8), ADD COLUMN longitude DECIMAL(11, 8);
ALTER TABLE attendance ADD COLUMN device_id VARCHAR(255);